from src.util.constants import (
    LAMP_4_MAC_ADDRESS, LAMP_4_NAME, LAMP_5_MAC_ADDRESS, LAMP_5_NAME,
    LAMP_3_MAC_ADDRESS, LAMP_3_NAME, LAMP_6_MAC_ADDRESS, LAMP_6_NAME, LAMP_1_MAC_ADDRESS,
    LAMP_1_NAME, LAMP_2_MAC_ADDRESS, LAMP_2_NAME
)


mapping: dict[str, str] = {
   LAMP_1_MAC_ADDRESS: LAMP_1_NAME,
   LAMP_2_MAC_ADDRESS: LAMP_2_NAME,
   LAMP_3_MAC_ADDRESS: LAMP_3_NAME,
   LAMP_4_MAC_ADDRESS: LAMP_4_NAME,
   LAMP_5_MAC_ADDRESS: LAMP_5_NAME,
   LAMP_6_MAC_ADDRESS: LAMP_6_NAME
}