from src.util.constants import (
    BATHROOM_MAC_ADDRESS, BATHROOM_NAME, HALLWAY_MAC_ADDRESS, HALLWAY_NAME,
    KITCHEN_MAC_ADDRESS, KITCHEN_NAME, LAMP_MAC_ADDRESS, LAMP_NAME, LIVING_MAC_ADDRESS,
    LIVING_NAME, ROOM_MAC_ADDRESS, ROOM_NAME
)


mapping: dict[str, str] = {
   LIVING_MAC_ADDRESS: LIVING_NAME,
   ROOM_MAC_ADDRESS: ROOM_NAME,
   KITCHEN_MAC_ADDRESS: KITCHEN_NAME,
   BATHROOM_MAC_ADDRESS: BATHROOM_NAME,
   HALLWAY_MAC_ADDRESS: HALLWAY_NAME,
   LAMP_MAC_ADDRESS: LAMP_NAME
}